name: Compile Windows build manually

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-version:
    name: Extract Version from pubspec.yaml
    runs-on: ubuntu-latest
    outputs:
      VERSION_NAME: ${{ steps.extract_version.outputs.VERSION_NAME }}
      VERSION_NUMBER: ${{ steps.extract_version.outputs.VERSION_NUMBER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION_FULL=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          VERSION_NAME=$(echo $VERSION_FULL | cut -d '+' -f 1)
          VERSION_NUMBER=$(echo $VERSION_FULL | cut -d '+' -f 2)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_OUTPUT
          echo "Extracted Version Name: $VERSION_NAME"
          echo "Extracted Version Number: $VERSION_NUMBER"

  build-windows:
    name: Build Windows installer
    runs-on: windows-latest
    needs: get-version
    env:
      VERSION_NAME: ${{ needs.get-version.outputs.VERSION_NAME }}
      VERSION_NUMBER: ${{ needs.get-version.outputs.VERSION_NUMBER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: 3.44.1

      - run: flutter clean
      - run: flutter pub get

      - name: Copy .env file
        shell: pwsh
        run: Copy-Item .env.sample .env

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows
        run: flutter build windows --release

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Windows Installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /DMyAppVersion="${{ env.VERSION_NAME }}" windows\installer.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: build/windows/PiHoleClient_${{ env.VERSION_NAME }}_Windows_x64.exe
